#!/bin/csh

echo " "
echo " **************************************************"
echo " * Calc. derivatives of ln[pdf] for each v-state. *"
echo " **************************************************"
echo " "

set auto = $1
set mdn = `more ../current_md_num`
set nvs = `more ../current_vst_num`
if ( $mdn < 10 ) then
  set mdn_str = "0${mdn}"
else
  set mdn_str = "${mdn}"
endif

  echo " "
  echo  "  MD No. ="  ${mdn}
  echo  "  N. of v states ="  ${nvs}
  echo "  "

  set sfac = `head -1 fac.squeeze `
  echo " squeezing factor = " ${sfac}
  echo "         used to defuse down the large derivatives. "
  echo "  "

  echo " "
  echo " Now calculate derivatives."
  echo " May I proceed? "
  echo " If OK, input 1.  If No, input any number else 1. "

  if( $auto == 1 ) then
    set ok = 1
  else
    set ok = $<
  endif
  if( $ok == 1 ) then
    echo " OK. I proceed. "
    goto p1 
  endif

  echo " I stop here. "
  echo " "
  exit
#*************************************
p1:

  ifort  -o aaa.exe  derv_poly.f 

  set dir = cal${mdn_str}_mcmd1

  @ ii = 1
  while( $ii <= $nvs )
    echo $ii
# <I>
    ln -s  ${dir}/b${ii}.fort.20   fort.50
    ln -s  ${dir}/range.s${ii}  fort.60

#<O>
    ln -s ${dir}/s${ii}.derv.poly  fort.51
    ln -s ${dir}/s${ii}.derv.dat  fort.52 

    ./aaa.exe  < fac.squeeze > out3
    rm fort.*    

    @ ii ++
  end

  rm aaa.exe
  cp  fac.squeeze  ${dir}
  mv  out3  ${dir}

#*************************************
  rm *.tar  
  cp -r md${mdn} md${mdn}_f
  tar cvf  md${mdn}_f.tar  md${mdn}_f
  rm -r md${mdn}_f

  echo " "
  echo "  end of all "
  echo " "
#*************************************
  exit

