#!bin/csh

  ifort -o aaa.exe  block.f
################################################# 
set auto = $1
echo "auto = $auto"

set done = `more ../current_md_num`
set nst = `more ../current_vst_num`
if ( $done < 10 ) then
  set done_str = "0${done}"
else
  set done_str = "${done}"
endif

echo " "
echo " ************************************************************"
echo " * 1) Output entire pdf by concatenating all v-state pdf's. *"
echo " * 2) Output block ranges.                                  *"
echo " ************************************************************"
echo " "
echo " MD done = " $done
echo " N. of v-states = " $nst
echo " "
echo "  Input 1, if OK. "
echo " "


  if( $auto == 1 ) then
    set ok = 1
  else
    set ok = $<
  endif
  if( $ok == 1 ) then
   echo " OK. I proceed. "
   goto p1 
  endif
  echo " I stop here. "
  exit

################################################# 
p1:

# <I>
  ln -s ../current_vst_num  fort.10
# <O>
  ln -s cal${done_str}_mcmd1/all_derv.dat  fort.80

@ ii = 1
while( $ii <= $nst )
  echo $ii

# <I>
  @ nn = 100 + $ii
  ln -s cal${done_str}_mcmd1/s${ii}.simple_fort.20  fort.${nn}
# <O>
  @ kk = 400 + $ii
  ln -s cal${done_str}_mcmd1/b${ii}.range  fort.${kk}

  @ ii ++
end

./aaa.exe > cal${done_str}_mcmd1/out2

rm fort.*
rm aaa.exe 
####################################################
exit


