#!/bin/csh

gfortran -o aaa.exe  integ.f
#*******************************************
echo " "
echo "*************************************************************"
echo "*  <<files are made for fitting in the subsequent step>>    *"
echo "* 1) Output pdf & range for each v-state.                   *"
echo "*    If simulation had been done with tmat =/= 1            *"
echo "*    the program integ.f resets pdfs as done with tmat = 1. *"
echo "* 2) The entire range is output.           (not used)       *"
echo "* 3) Concatenate v-state ranges into blocks & output.       *"
echo "* 4) Integrate v-state pdf's into entire pdf.               *" 
echo "*************************************************************"

set flg_neighbor = $1
set auto = $2

  head -1 ../current_situation > aaa
  set mdn = `more aaa`
  rm aaa
  head -2 ../current_situation > aaa
  tail -1 aaa > bbb
  set nvs = `more bbb`
  rm aaa bbb

if ( $mdn < 10 ) then
  set mdn_str = "0${mdn}"
else
  set mdn_str = "${mdn}"
endif


  echo " "
  echo  "  MD No. ="  ${mdn}
  echo  "  N. of v states ="  ${nvs}
  echo "  "

  set dir = cal${mdn_str}_mcmd1
  set dir1 = ../v_distrib/${dir}
##   set dir1 = ../Markov/md${mdn}_Mk
  set dir2 =  ../../${dir}

  echo "  positiojns of twpo input files:"
  echo "      " $dir1
  echo "      " $dir2 "   <------------------- OK? "
  echo "  "

  echo " May I proceed? "
  echo " If OK, input 1.  If No, input any number else 1. "

  if( $auto == 1 ) then
    set ok = 1
  else
    set ok = $<
  endif
  if( $ok == 1 ) then
   echo " OK. I proceed. "
   goto p1 
  endif
  echo " I stop here. "
  echo " "
  exit
#********
p1:  


  echo " Generate directory " $dir
  rm -r $dir
  mkdir $dir

#  Link I/O files.

  @ ist= 1
  while( $ist <= $nvs )
    echo " file linking:" $ist

# <I>
    @ idev = 100 + $ist
    set fil = ${dir1}/v_pdf/s${ist}.pdf 
##  set fil = ${dir1}/s${ist}.pdf 
    ln -s  $fil  fort.${idev}
# <O>
    @ idot = 200 + $ist
    ln -s  ${dir}/s${ist}.pdf  fort.${idot}
    @ idotr = 300 + $ist
    ln -s  ${dir}/range.s${ist}  fort.${idotr}
    @ iotn = 400 + $ist
    ln -s  ${dir}/range.b${ist}  fort.${iotn}

    @ ist ++
  end

# <I> 
   ln -s ../../${dir}/ttp_v_mcmd.inp  fort.501
#   set aaa = ${dir2}/inp_data/aus_coef_md${mdn}.inp
#   ls -la $aaa
#   ln -s $aaa  fort.501
###  ln -s scale.fact fort.11   <-- do not use this file any more.
# <O>
  ln -s ${dir}/range.entire  fort.90

  echo ${nvs} > work1
  ./aaa.exe < work1 > ${dir}/out1

  rm aaa.exe  fort.*
  rm work1
#********
  echo " "
  echo " integrate pdfs. "
  @ ii = 1
  while( ${ii} <= ${nvs} )
    echo "#" ${ii}
    more  ${dir}/s${ii}.pdf >> ${dir}/entire.pdf
    @ ii ++
  end

  exit
#*************************************************

